Sprint 3
tmj1/middle.messenger.praktikum.yandex pull request #5
Opened 2022-12-20 09:18 UTC by tmj1

First pull request of the Sprint 3

2022-12-22 03:14 UTC, maks88sgt requested changes
Привет! Отличная работа. У тебя получился хорошо структурированный проект с довольно чистым кодом. В целом все критерии спринта выполнены, но я предлагаю поправить мелкие моменты перед тем как идти дальше. 
Также к сожалению я не смог потестировать приложение в целом, т.к. бекенд не работал в момент проверки. Но надеюсь там все ок.

2022-12-22 03:14 UTC, maks88sgt commented on server.js
> +const pathName = path.join(__dirname, '../dist/index.html');
При локальном запуске сервер дает ошибку, т.к. пытается искать dist/index.html уровнем выше.

2022-12-22 03:14 UTC, maks88sgt commented on package.json
> +    "express-handlebars": "^6.0.6",
Давай зафиксируем версию, как и остальными зависимостями

2022-12-22 03:14 UTC, maks88sgt commented on src/api/AuthAPI.ts
> +  public signup({ email, login, first_name, second_name, phone, password }: SignupType) {
Не часто встречается использование public модификатора, потому что это значение - по умолчанию. Но это ок, если так принято в команде например. Об этом даже сказано в документации https://www.typescriptlang.org/docs/handbook/2/classes.html#public

2022-12-22 03:14 UTC, maks88sgt commented on src/components/avatar/avatar.ts
> +          srcAvatar !== 'undefined' && srcAvatar !== 'null'
Думаю что можно упростить это не потеряв логику
```suggestion
          !srcAvatar
```

2022-12-22 03:14 UTC, maks88sgt commented on src/components/user/user.ts
> +        props.users !== 'undefined' && props.users.length > 0
Здесь тоже можно чуточку проще
```suggestion
        props?.users?.length ? ... : ...
```

2022-12-22 03:14 UTC, maks88sgt commented on src/core/BrouseRouter.ts
> +    let route = this.getRoute(pathname);
Значение переменной не меняется по ходу исполнения кода, поэтому лучше здесь будет использовать const

2022-12-22 03:14 UTC, maks88sgt commented on src/services/MessagesService.ts
> +  public connect({ userId, chatId, token }: any) {
Желательно конечно затипизировать аргументы и избавиться от any

2022-12-22 14:24 UTC, tmj1 commented on src/core/BrouseRouter.ts
> +    let route = this.getRoute(pathname);
и правда, спасибо - сделано

2022-12-22 14:39 UTC, tmj1 commented on src/services/MessagesService.ts
> +  public connect({ userId, chatId, token }: any) {
сделано

2022-12-22 14:39 UTC, tmj1 commented on src/api/AuthAPI.ts
> +  public signup({ email, login, first_name, second_name, phone, password }: SignupType) {
принято

2022-12-22 14:43 UTC, tmj1 commented on server.js
> +const pathName = path.join(__dirname, '../dist/index.html');
исправлено

2022-12-22 14:48 UTC, tmj1 commented on package.json
> +    "express-handlebars": "^6.0.6",
зафиксированы

2022-12-22 18:02 UTC, maks88sgt commented
Привет! Спасибо за оперативные исправления, теперь все стало гораздо лучше. Сервер заработал и я смог потестить основной функционал приложения. Выглядит так, что обмен сообщениями не подключен. Вот скринкаст с багом 


https://user-images.githubusercontent.com/49103217/209197456-5a5f9301-1f28-4024-99ce-465eec7c0627.mp4

После нажатия для отправки сообщения не происходит ничего. И предыдущие сообщения из чата не загружаются. Давай поправим это

2022-12-23 02:39 UTC, maks88sgt requested changes
Привет. Теперь все работает как должно. Осталась крайняя проблема с работой сервера - ошибка с путями к файлам не исправлена и приводит к тому, что при обновлении страницы получаем ошибку сервера

2022-12-23 02:39 UTC, maks88sgt commented on server.js
> +const pathName = path.join(__dirname, '../dist/index.html');
Здесь все еще осталась проблема. При обновлении страниц с урлом отличным от дефолтного получаем ошибку. Посмотри повнимательнее на код своего сервера

2022-12-23 07:43 UTC, tmj1 commented on server.js
> +const pathName = path.join(__dirname, '../dist/index.html');
код сервера переформатирован

2022-12-24 14:02 UTC, merged